### PR TITLE
Added support for square radial fans.

### PR DESCRIPTION
**Pull request by martinbudden**
square_radial_fan

### CODE REVIEW

**Comment by nophead** [comment]
Fan guard and mounting screws don't work with this because the mounting holes are at the bottom instead of the top. I.e. the screws are offset by the panel thickness plus the guard thickness from the base thickness, rather than the full height of the fan. Also the fan_guard needs to take the offset into account.

Probably it wouldn't need a guard as the blades are too short and close to trap a finger.

**Comment by nophead** [comment]
Actually I think it is fairly easy to fix, so I will do it.

**Comment by martinbudden** [comment]
I've adjusted the offset for the mounting screws:
radialFanWithBolts

The fan guard doesn't work, but these fans never seem to have guards, just like blower fans.

**Comment by nophead** [comment]
The main problem is axial fans are panel mounted, so the screws go through the panel and ```fan_holes()``` makes a cut out and fan_guard can make either a guard or a grill, like in power supplies.

image

These functions could all be modified to take the offset into account and the screws go from above but does it make sense, would it ever be panel mounted like that?


This is actually a radial fan, which I have called a blower.

image


In particular it is screwed through its base to something underneath and it has a rectangular exit port. So logically it is one of these even if it has a different case shape.

**Comment by martinbudden** [comment]
A radial fan would never be mounted like that, since it would be blowing the air in the wrong direction, so I don't think there is any point modifying those functions.

I did think of making the square radial fan a type of blower, but the blower code doesn't suit this.

I've only seen these square radial fans used on hotends, eg:

image

**Comment by nophead** [comment]
Yes they are good for part cooling and perhaps air assist on a laser. That
is what I use radial blowers for but I need the exit port details to make
mating ducts.

It is unfortunate the shape is more like an axial fan but it isn't one.

**Comment by nophead** [comment]
For example I use one here:

image

I would expect to be able to change the type to your square one and everything would adapt but it won't if it is modelled as an axial fan.

**Comment by martinbudden** [comment]
If you like, I could try and redo it as a blower type.

**Comment by nophead** [comment]
Yes please. I agree the code to draw it will get more ugly but the interface should be more correct, which is what matters to the end user.

**Comment by martinbudden** [comment]
OK, will do.

**Comment by martinbudden** [comment]
Closing. Superseded by https://github.com/nophead/NopSCADlib/pull/98

**Pull request closed without merging**
