### PR TITLE
Add rectangular LEDs

### PR DESCRIPTION
**Pull request by mmuman**
As per https://www.futurlec.com/LED/Red_2x5mm_LED.shtml

### CODE REVIEW

**Comment by mmuman** [comment]
I suppose I should reindent the rest?

**Comment by nophead** [comment]
Yes please.

**Comment by mmuman** [comment]
Done.

**Comment by nophead** [comment]
This broke the LED test and the LED bezel test. Please run tests before submitting any PRs.

**Comment by mmuman** [comment]
Oh I didn't notice there were tests, sorry :sweat_smile:

**Comment by nophead** [comment]
The tests make the pictures and the readme documentation.

**Comment by mmuman** [comment]
I noticed when reading the log, nice. I myself use OpenSCAD + make to generate documentation for some projects. :-)

**Pull request merged**
