### PR TITLE
Added size and slot convenience functions. Added non-rounded hole.

### PR DESCRIPTION
**Pull request by martinbudden**
Non-rounded hole is for when you need to bridge around the rocker hole.

### CODE REVIEW

**Comment by nophead** [comment]
Why not rounded? The slot is longer than the switch and the tabs only make contact away from the corners.

**Comment by martinbudden** [comment]
The non-rounded form is for when you need to bridge the hole around the rocker switch, for example if you are putting it into a vertically printed panel.

**Comment by nophead** [comment]
I normally use horizontal = true to indicate that. If the radius was important it would turn it into a tearslot but in this case it isn't.

**Comment by martinbudden** [comment]
I thought about using `horizontal = true`, but it seemed confusing for the rocker switch. For a screw, the meaning is clear, since symmetry means there is only one horizontal orientation. However for the switch, there are two ways to rotate it that could both conceivably mean horizontal only one of which requires a non-rounded hole, so I opted for a direct description of what the parameter was for.

**Pull request merged**
