### PR TITLE
Servo motor, E40 bracket, linear rails, nema8, ++

### PR DESCRIPTION
**Pull request by niclash**

### CODE REVIEW

**Comment by niclash** [comment]
I'll spend time to fix the issues that you raise, once I have am OpenSCAD "nightly" that works and have time to fiddle around with it.

**Comment by nophead** [comment]
Why do you need to use a nightly? NopSCADlib works with the latest release and any snapshot up to 01/05/21. I am using OpenSCAD 2021.05.01.ci7809 to get the improved drawing speed but it does have regressions in the customiser, which has been fixed in later snapshots that I can't use. Nobody seems interested in fixing the dollar variables regression.

I will have a look at fixing these PR issues myself.

**Comment by niclash** [comment]
I didn't notice that Debian has updated to a recent OpenSCAD release. It used to be very old. So, I change "when/if I have time, unless you beat me to it"

**Comment by nophead** [comment]
I fixed the screws sockets.

image

**Comment by nophead** [comment]
I fixed the NEMA8 by making the thread size a property and allowing black endcaps.

image

Can you confirm it looks like this, has M2 screws holes and a 5mm shaft. A lot of NEMA8s have 4mm shafts.

**Comment by nophead** [comment]
Please can you give a link to the lead nut you are trying to model. I can't find anything that matches your dimensions.

**Comment by niclash** [comment]
When I made the parts, I didn't own them yet... Now I do.

Axel; 5mm, 22mm long from "protrusion plate"
Protrusion plate; 22mm in diameter, 2mm up from front plate.
Front plate; 42x42mm (actually slightly less), M3 holes 31mm apart, 10mm thick
Body; 48mm tall, bottom plate 11mm (indent 2mm) thick,


image

HTH

**Comment by nophead** [comment]
That is a NEMA17 not NEMA8.

**Comment by niclash** [comment]
Ok, sorry. My NEMA8 is with hollow shaft (for vacuum). Maybe that accounts for shaft diameter inconsistency.

Axel; 5mm, 10.6mm long from "protrusion plate", 7.3mm at the back
Protrusion plate; 15mm in diameter, 1.6mm up from front plate.
Front plate; 20x20mm (actually slightly less), M2 holes 16mm apart, 6mm thick
Body; 30mm tall, bottom plate 8.1mm thick,

image

**Comment by niclash** [comment]
When ordered, I simply requested 16mm diameter, 2 different lengths, 10mm "lift" and matching mounting blocks, nut, nut housing and motor coupling. Never received a drawing.

SFU1610 ballscrew; http://www.ywsbearing.com/CNC-machine-part-high-precision-16mm-diameter-C7-C5-precision-ball-screw-SFU1610-with-nut-and-support-unit-BK12-BF12-pd77372377.html

Large diameter; 48mm
Straight diameter; 40mm
Length; 42.5mm
Body diameter; 28mm


image

**Comment by nophead** [comment]
How many starts does the thread have?

**Comment by niclash** [comment]
2

**Comment by nophead** [comment]
image

The thread doesn't make a lot of sense because it is trapezoidal rather than ball races but you don't see it when assembled.

The length looks too short. It includes the flange.

**Comment by nophead** [comment]
I have the exact same NEMA8, so the model will be useful when I get around to building my pick and place machine. Seems to use a smaller JST connector than the NEMA17s, so I will have to model that as well.

**Comment by niclash** [comment]
Mine; https://github.com/niclash/DreamPlacer 

(yeah, big because I want feeders that I never change component type in)

Mechanically it is all built, and working on electrical now.

**Comment by nophead** [comment]
Great name for a PnP machine.

**Comment by nophead** [comment]
I started looking at the servos. Why are they modelled as a cylinder that is bigger than the face plate? As far as I can tell they look like this:

image

Not like this:

image

**Comment by nophead** [comment]
I think you have misinterpreted this diagram

image

The dashed line is the hole pitch circle, not the body.

I will model it as a rectangle with quadrants removed from the corners. How deep is the cylinder on the back?

**Comment by nophead** [comment]
Please can you supply the dimensions of the M8 sliding nut. Does it look something like this?

image

**Comment by niclash** [comment]
Servo; Yeah, possibly. It is now a year ago, so I honestly don't remember, other than I made it before I had them in real life.

Depth behind mounting plate face; 152mm
From cylinder circumference to top of electric input; 86mm

IMG_20210831_094218
IMG_20210831_094225
IMG_20210831_094230

**Comment by niclash** [comment]
Sliding nut; The ones I bought are different. It has spring ball and can be inserted through the slit (rather than from the end). 22mm x 13mm
M5, M6 and M8 variants are all the same dimensions with different drill+tap.

IMG_20210831_095420
IMG_20210831_095432
IMG_20210831_095344
IMG_20210831_095354
IMG_20210831_095400

**Comment by niclash** [comment]
sorry for the somewhat poor photo quality

**Comment by nophead** [comment]
The servos currently look like this:

image

I have changed a lot of things:

- They are now called `servo_motors` because we have `stepper_motors` and `BLDC_motors`. I will leave `servos` for RC type servos.
- The origin is now in the middle of the faceplate rather than the top of the boss to be consistent with steppers.
- I renamed mount to faceplate as I think it is a more appropriate name.
- I modelled the faceplate  in 2D as a rounded_square with four circles subtracted and then extruded. That is simpler than hulling four corners and faster than subtracting cylinders.
- I simplified the shaft code by using `slot()` to make the keyway.
- Not sure why you model with all the primitives centred. For an object like this that isn't centred vertically it is a less code to model with primitives that are not centred. It gets rid of a lot of divide by 2s.
- I added `servo_motor_width(type)` and `servo_screw_positions(type)` to make it easier to use by hidings the fact it is made from three objects. 
- I removed the strings from the faceplate and shaft objects because they are not vitamins in themselves and don't appear on BOMs or the documentation.
- I haven't modelled the cable port as I don't have enough dimensions but it would be easy to add. I have also guessed a few dimensions but they are easy to change.

**Comment by nophead** [comment]
I have pushed everything apart from the sliding nut and the extrusion brackets that need more work.

This is what the NEMA8 looks like.

image

The one on the left is a standard NEMA8 with a single 4mm shaft. The one you want with two hollow 5mm shafts I have named NEMA8BH.

**Comment by nophead** [comment]
The E40_inner_corner_bracket doesn't look right because the code is not parametric enough but I don't have one to measure.

If you want me to add it please provide a photo and all the dimensions and the screw size.

image

**Comment by niclash** [comment]
I am feeling guilty for all the work you are doing...

Width; 18.6mm
Short side; 31.2
Long side; 37.8
"Gap"; 7mm
"Protrusions for fitting extruded alu"; 8.2mm, except one (inside of side with 2)  of the 3 that is 8mm.
Inset screws; M6
Inset (short side) 10mm from edge (not the corner)
Inset (short side) 13mm from edge (not the corner)

IMG_20210901_142727
IMG_20210901_142734
IMG_20210901_142742

**Comment by nophead** [comment]
@martinbudden, what is part_thickness here: https://github.com/nophead/NopSCADlib/blob/master/vitamins/extrusion_bracket.scad#L115

It seems to need to be equal to the extrusion thickness. Do you envisage the corner brackets being used without extrusions?

**Comment by martinbudden** [comment]
@nophead , yes this is the extrusion thickness. I set it as a parameter rather than having to pass the extrusion type as a parameter.

However I think that the extrusion corner brackets are actually repurposed furniture brackets and are also used for joining bits of wood together in furniture.

**Comment by nophead** [comment]
I have added a default extrusion and t-nut to the bracket object properties and those are now used to get the defaults for `part_thickness`, `screw_type`, `nut_type`  and `max_screw_depth`.  I did that so that the examples in the test work without having to override all those parameters and makes the assembly easier to use in a project.

I also had to do the same to the inner bracket because a lot of things were hard coded that need to be extrusion specific or derived from the base t-nut.

image

**Comment by nophead** [comment]
This is what it currently looks like:

image

@martinbudden had modelled the inner brackets as two t-nuts linked by an arm but actually the long side is different so that it can be fitted to the extrusion either way around. I modelled that from your dimensions, i.e. arms 8.5mm thick and the T 4.7mm thick and 18.6mm wide but it doesn't fit the extrusion.

image

Any idea what is wrong. Is it the extrusion or the bracket?

I also modelled the sliding ball t nut but I had to guess a lot of the dimensions. It is generated by setting Y2 = 0 for sliding t_nut.

image

Is it a 4mm ball offset 4mm for the end?

What is the total height and what is the stem height?

What is the hole offset from the end and is it constant for the different screw sizes?

**Comment by nophead** [comment]
Hmm, I thought E2020, etc, extrusions were a standard but they seem to vary quite a lot. The central hole can be 5mm or 4.2mm. The inner slot can be 11mm or 12mm. The gap can be 6 or 6.2mm. The wall can be 2mm or 1.8mm. The spar can be 1.2mm or 2mm. The Chinese ones I have match this drawing so I am minded to amend the definition to match.

image

**Comment by niclash** [comment]
Correct, there is no standard, as I think some BigCo (Bosch?) has patents/trademarks related to some shapes and people have worked around that. What seems to be "standard" are the widths nomenclature 2020, 3030, 2040 and so on as well as center hole diameter when one is there at all. I bought my ones locally in Sweden (with their own manufacture), they had several similar profiles, same dimension and hole size, but varied in strengths and weight (i.e. amount of material).

So, "I want those, and matching T-nuts and inner brackets" was how I approached it.

**Comment by niclash** [comment]
Regarding my 4040 T-nuts;
Ball in ~4.2mm from edge.
M3 and M4 are 9mm from edge, M8 is ~7.2 from edge. (I don't have any M6)

IMG_20210902_144410

**Comment by niclash** [comment]
In case not obvious; The ball on the T-nut has spring and intended to not slide too freely in the alu slot.

**Comment by nophead** [comment]
I modelled the ball T-nut so the hole has its inner edge in the centre and that seems to be close enough. Please can you confirm the total height and the stem height and then it is good to go.

I added chamfers to the inner corner brackets and made the 2020 extrusions match mine and then they just fit as they do in real life as I have these parts. I now realise why they have the shape they have and I have added a backwards option to allow them to be inserted the other way, which makes a smaller junction.

image

I haven't got any 4040 extrusions and even using a popular size where the walls are 4.32mm instead of 5.5mm doesn't quite allow them to fit but I haven't got any 4040 or that size corner brackets.

image

@martinbudden where did the extrusion dimensions come from? Do they match the extrusions you have?

@niclash even the centre holes are not standard. Some 2020 are 4.2mm which can be tapped for M5 but mine are 5mm, which could be tapped for M6.

**Comment by nophead** [comment]
Actually I do have some 4080 on my CNC router that I bought, rather than designed. It has 4mm walls and the central spars are 2.4mm. With those dimensions the inner brackets easily fit.

image

My 4080 has a round central tubes with ribs and the corner holes are square. Also all more extrusions have a recess in the outer slots. I seem to have opened a big can or worms!

**Comment by niclash** [comment]
Anecdote; My father had a "exhibition booth system" back in the mid-1970s, and is the oldest alu profile of these shapes that I know of. I recall that the slots were to both hold the walls as well as mounting lights, shelves, tables and so on. I still have a small piece of that...

IMG_20210903_105143

**Comment by nophead** [comment]
I wonder why there is a notch in the sides of the central tube. Seems like a point of weakness with no real function. Perhaps to centre a drill if you want to drill through the side?

**Comment by niclash** [comment]
Also, I bought my material att https://www.rollco.eu, and they have an interactive system "CAD-files" to get exact drawings on most parts they make.

**Comment by niclash** [comment]
Can of worms; Yes!

"notch" ; yes, as drill guide.

**Comment by nophead** [comment]
I don't wish to be rude but unless you confirm the dimensions of the sliding ball nut and the actual 4040 extrusions you have I will just push what I have. 

With the skinny 4080 extrusion, the ball doesn't touch. So I need the wall and spar thickness of the 4040 and the height and stem of the t-nut.

image

I think I used some of those when I built the mill ten years ago but not sure. I 3D printed a lot of the t-nuts I used to add cable clips and limit switches, etc.

My 4080 is odd in that it has ridges in two of the corner holes but not the other two. No idea why.

IMG_20210903_114833927_HDR

**Comment by niclash** [comment]
I made some crude dimensions from the DXF I got from manufacturer.

image

**Comment by niclash** [comment]
Screenshot_20210903_165218

**Comment by niclash** [comment]
Screenshot_20210903_165711

**Comment by nophead** [comment]
With those dimensions the ball meets, although the centre square dimension seems to be missing:

image

But the inner bracket clashes badly, any idea what is wrong?

image

The extrusion is totally different to the E4040 in the library. It has smaller slots and holes, thinner walls but much thicker spars. I think I will need to add more extrusion types if anybody has used the existing ones.

**Comment by nophead** [comment]
IIRC @martinbudden added both the original extrusions and the inner brackets. But I don't think the inner brackets fit the original E2020 extrusion? They certainly don't after I remodeled the longer end to be double sided. Where yours actually like this or where they as you modelled them as two normal T nuts?

image

**Comment by niclash** [comment]
When I added the bits I needed, I had not chosen a vendor yet. So, not sure where I got the dimensions from. And frankly, I didn't care that much whether it was pixel-perfect along non-critical dimensions. And I suspect that trying to be totally true to reality is a (s you put it) can of worm, and never ending headache. At some point (long past in my book) it is "good enough".

**Comment by niclash** [comment]
I am really grateful for all the work you have put into this and the library as a whole, since I am mentally incapable of operating something like FreeCad, and was delighted to be productive with OpenSCad (since I am a professional programmer) and finding this library saved me a ton of time. THANKS A LOT!

**Comment by nophead** [comment]
I can fully appreciate that once you have built the machine and all the parts fitted you don't care about a few pixels. The problem is the main reason for using this library to make assembly views is to check that things fit before making it. Anybody using the inner corner brackets would assume they don't fit the extrusions. 

When I model my actual 2020 extrusions I find they do fit on screen and they do fit in reality.  The bracket for 2020 model was contributed by Martin and it matches the ones I have. I can't explain the E2020 model in the library that Martin contributes as that does not fit.

And your bracket dimensions would fit my 4080 extrusion but don't fit Martin's 4040 model and don't fit your 4040 drawing.

I think all I can do is add my 2020 model with a new name and use that to show off the the smaller bracket and add a new 4040 model with a new name based on my 4080 and use that to show off your bracket.

**Comment by nophead** [comment]
I have pushed my changes to extrusions and T-nuts so that should be all of your original PR implemented.

I added models of the extrusions I own that actually work with the brackets so they are the defaults but you can pass an alternative extrusion type.

image

If you solve the mystery of the clash feel free to open a PR with an alternative extrusion model or bracket model. My best guess is neither you or @martinbudden are actually using extrusions that match your models. In the real world they seem to have a lot less aluminium!

**Pull request closed without merging**
