### PR TITLE
Changed rail carriage coloring to be green with red endpiece

### PR DESCRIPTION
**Pull request by martinbudden**
This matches the common form and gives a good visual clue for the part.

### CODE REVIEW

**Comment by nophead** [comment]
This would need to be parametric because my rails are black, hence why I modelled them that way.

**Comment by martinbudden** [comment]
I've parameterised the coloring of the carriage. I wasn't sure if you'd prefer it done by adding a parameter to the `carriage` `module`, or making the colors part of the property of the `carriage` type. I've done the former, but while doing it I thought the latter may be a better approach. What's your view?

**Comment by nophead** [comment]
I think the way you have done it is best because otherwise it would require duplicating all the object definitions.

**Comment by martinbudden** [comment]
OK. Anything else you'd like me to change in this?

**Comment by nophead** [comment]
No it looks good, I will merge it after I have merged my own changes,

**Pull request merged**
