### PR TITLE
Conditionally rendered pulleys to speed up drawing.

### PR DESCRIPTION
**Pull request by martinbudden**
Also changed "silver" to silver.

### CODE REVIEW

**Comment by nophead** [comment]
LOL, I am currently trying to find missing renders to speed up drawing! Do you mean to speed up the rendering()?

**Comment by martinbudden** [comment]
Yes, that's what I meant.

**Comment by nophead** [comment]
Having tried both versions a few times I don't see any consistent improvement in the test times.

I think that is because when the difference has only one operand it gets short circuited and then the render only works on the linear extrude of the teeth, which is just a polyhedron already, so render takes no time in that case.

**Comment by nophead** [comment]
Note also some release candidates made pulleys a lot slower, see https://github.com/openscad/openscad/issues/3529

**Comment by nophead** [comment]
OK I merged a version that should be optimum on all versions. It always renders the difference but avoids the difference altogether when there isn't a hole.

**Comment by martinbudden** [comment]
OK, thanks for checking into this.

**Pull request merged**
