### PR TITLE
Added optional jst connector to stepper motors.

### PR DESCRIPTION
**Pull request by martinbudden**
Only added it to the NEMA17 motors, since I don't have any of the other types to confirm correctness.

### CODE REVIEW

**Comment by nophead** [comment]
Thanks, something on my todo list.

The only motors on the list that have connectors are the NEMA17M and NEMA17M8 sizes that I got from RoboDigg. The larger and smaller ones I posses just have wires. What sizes are you using?

I would be happy to add connectors to just those two but if you want the larger and smaller motors to have connectors we will need to have two variants of them.

**Comment by martinbudden** [comment]
I've just got NEMA17 motors. Some with wires and some with JST connectors. I don't think we need two variants of those - if the motor with the JST connector fits, then so will the one with wires.

As for the other sizes, I think a good approach is only to add a variant with a connector when you get one in your possession, so that you can check the dimensions.

**Comment by nophead** [comment]
Perhaps it should be a parameter of the module rather than a property of the object to avoid having two variants then.

**Comment by martinbudden** [comment]
Yes, that's a better idea. I'll update the PR.

**Comment by nophead** [comment]
The connector seems to be offset from the tab.

image

**Comment by nophead** [comment]
I fixed it by using the straight version of the connector and the width of the connector / 2.

**Comment by martinbudden** [comment]
The gap between the connector and tab is deliberate - on stepper motors there is a tab of a circuit board there, which I didn't bother drawing. By moving the connector closer to the tab you have now made it dimensionaly incorrect.

**Comment by nophead** [comment]
OK I will add the PCB then. Its hard when I don't have any parts with me.

Do you know how they stop the pins shorting to the metal. Is there a gap and some insulation or is the tab hollow?

**Comment by nophead** [comment]
Looks like there is no standard position for this. Here are the dimensions of the 40mm motors I have.

image

It sticks out further and is mounted higher than your version. Do you have an alternate drawing?

**Comment by martinbudden** [comment]
I made this using dimensions I measured rather than from a drawing. I guess it is good enough at the moment. Having the connector ensures there are no nasty surprises when assembling and realising there is no room for the connector.

**Comment by nophead** [comment]
I found out the connector is actually smaller because it is a JST PH series with 2mm pitch. I will attempt to model that and make it match the drawing as that is the only NEMA17 motor I have with a connector. The metal tab is a lot thicker, so I assume you must have a different motor.

**Comment by martinbudden** [comment]
It seems like the size of the tab is not standardised. I think the important thing is to slightly oversize rather than undersize, that way if the motor fits in the drawing it is more likely to fit in actuality.

**Comment by nophead** [comment]
I think the tab thickness only depends on the end cap height, so I have made that parametric and set it correctly on the NEMA17 I have that has a connector. Basically the connector butts up the laminations and the tab is below that by the connector height and the standard thickness of a PCB, 1.6mm, even though it looks like some PCBs are thinner.

I made the JST connector more parametric and modelled the PH connectors used by the motors. In doing so I made the pin offsets of the XH connectors more accurate. If you have any on a PCB you with need to move vertical ones by 0.525mm and right angle ones by 0.4mm as connectors have their origin on the pin line.

image

**Pull request merged**
