### PR TITLE
update nuts.scad table comment

### PR DESCRIPTION
**Pull request by drf5n**
Change comment about nut sizes from radius to diameter.

### CODE REVIEW

**Comment by nophead** [comment]
Why make_all.py? I just type make_all so make_all is the command, make_all.py is the script that implements it.

**Comment by drf5n** [comment]
I see-Windows omits the extension that one would need on Mac and Linux.

**Comment by drf5n** [comment]
I backed out the make all commit from this patch.  Now it's just a comment update.

**Comment by nophead** [comment]
Thanks.

**Pull request merged**
