### PR TITLE
Added ability to use microswitch on a pcb.

### PR DESCRIPTION
**Pull request by martinbudden**

### CODE REVIEW

**Comment by martinbudden** [comment]
Withdrawn.

**Comment by nophead** [comment]
May I ask why?

**Comment by martinbudden** [comment]
Sorry the late reply. I felt that choosing the microswitch from the microswitches array was not really a very satisfactory solution - to susceptible to being broken by future changes.

**Comment by nophead** [comment]
I see, yes I agree that is too brittle. I think you can just embed the object name in the PCB component list instead of an index.

**Pull request closed without merging**
