### PR TITLE
Added variants for the KP08 pillow blocks

### PR DESCRIPTION
**Pull request by Drachenkaetzchen**
This patch adds both 15mm and 18mm variants of the pillow blocks.

### CODE REVIEW

**Comment by nophead** [comment]
This didn't build, I had to fix the test routine. Please run the test before submitting PRs.

I have merged it but I think it highlights a bug in the drawing. There are gaps between the top of the webbing and the ring around the bearing. I think the real objects won't have gaps.

**Comment by martinbudden** [comment]
I was a little surprised to see that only the H parameter was changed in this PR. Generally the parameters are interrelated, so changing one will require changes to others.

I'll have a look at this and submit a fix in due course.

**Comment by Drachenkaetzchen** [comment]
> I was a little surprised to see that only the H parameter was changed in this PR. Generally the parameters are interrelated, so changing one will require changes to others.

I was surprised too when I had a look at several "datasheets" - everything else except the hole offset seems exactly the same, including the overall height of the pillow block.

> I'll have a look at this and submit a fix in due course.

Thanks!

**Comment by martinbudden** [comment]
OK, I've checked this. There is nothing wrong with Drachenkaetzchen's changes to the H parameter, however in my code the webbing is not drawn entirely correctly. I'll fix that.

**Pull request merged**
