### PR TITLE
Added dogbones with circles offset in x and y directions.

### PR DESCRIPTION
**Pull request by martinbudden**
Added dogbones with the end circles offset in the x and the y directions. Useful if you need a dogbone near the edge of a part.

### CODE REVIEW

**Comment by nophead** [comment]
Rather than adding four new modules why not just add two parameters x_offset and y_offset defaulted to undef?

Then do x_offset = is_undef(x_offset) ? r / sqrt(2) : x_offset;

**Comment by martinbudden** [comment]
Good idea. I'll alter the PR.

**Comment by nophead** [comment]
I was thinking the same for dogbone_rectangle(). Just add x_offset and y_offset defaulted to undef and pass them to dogbone_square().

**Comment by martinbudden** [comment]
I think `dogbone_rectange_x` and `dogbone_rectangle_y` are useful wrapper functions, it saves having to think about how much the offset is, and in which direction for the dogbone you want.

**Comment by martinbudden** [comment]
OK, I've made the wrapper functions as thin as possible.

**Comment by nophead** [comment]
I don't think I would use the wrappers as it would make a shape that needs filing. However I can see cases where a smaller offset can be used. If the hole is a clearance hole, they could be brought in to just touch at the corners and if the object that fits in the hole has a corner radius they could be brought in some more.

**Comment by nophead** [comment]
Actually I see the point now after looking at the images.

**Comment by martinbudden** [comment]
Yes, they are especially useful for doing the tabs on a sheet if you want to construct a box out of interlocking sheets, ie to do what woodworkers call finger joints.

**Comment by martinbudden** [comment]
Here's and example of a finger joint using the new dogbones:

dogbones

**Comment by nophead** [comment]
Nice, we should probably add pictures like to the blurb.

**Comment by martinbudden** [comment]
Once we've got the carbon fiber sheets in, we can add some pictures using those.

**Pull request merged**
