### PR TITLE
Added sheet with checkerboard texture to simulate carbon fiber.

### PR DESCRIPTION
**Pull request by martinbudden**
When rendered, it looses its texture.

### CODE REVIEW

**Comment by nophead** [comment]
The way I model sheets is to do it all in 2D with sheet_2D and then use render_2D_sheet() unless it has 3D features like countersinks and then I use sheet() and render_sheet().

I am thinking render_2D_sheet() could be made to work with the woven pattern by doing 2D intersections with the weave and then linear_extruding each of them and then colouring. 

woven_sheet() would take a 2D child of the shape and then intersect it with one checker-board, linear_extrude and colour it and then do the same for the inverse checker-board. That would make it much simpler as it just needs enough squares, any excess gets trimmed by the intersection to take care of the remainder bits at the edge. You then don't need fillet to trim the corners, you can just pass a 2D sheet, which has the advantage they will be the correct colour. Currently they are green.

**Comment by martinbudden** [comment]
Yes, that would make the edge handling easier. I'll look into it.

**Comment by nophead** [comment]
I think render_sheet() could be made to sort of work by using projection() to sample just below the top and bottom surface and making two thin textured veneers. The edges and internal details would be one solid colour though.

**Comment by martinbudden** [comment]
@nophead , can you have a look at this now, to see what you think?

**Comment by martinbudden** [comment]
I think this is working fully now.

**Pull request merged**
