### PR TITLE
Updated tests.py to better support generic testing.

### PR DESCRIPTION
**Pull request by martinbudden**
Partial fix to https://github.com/nophead/NopSCADlib/issues/81 .

Could you add a change to allow the filename to be specified on the command line - that would be sufficient to make this usable for me.

### CODE REVIEW

**Comment by nophead** [comment]
I don't understands this PR. It breaks the library because tests is where the test files live. It isn't a category of things to be tested.

I get this:

image

What do you have in the test directory? Tests or things to be tested?

**Comment by martinbudden** [comment]
Ah, I see. I sort of assumed that everything in tests should be tested. I'll come up with a better PR.

**Comment by nophead** [comment]
I am working on it at the moment. I have used the presence of libtest.scad to decide if it is a library build or not.

Tests contains just the test code. It then looks in vitamins, utilities and printed to find the source code and uses that to categorise them in the table of constants. I think you need to put your code that is to be tested in the folders and the test code in test to mimic the library structure to make it work.

**Comment by martinbudden** [comment]
OK, that sounds good. I'll leave you to it.

**Pull request merged**
