### PR TITLE
Added PCB buzzer.

### PR DESCRIPTION
**Pull request by martinbudden**
Added a small buzzer of type used on PCBs. Size and color are defaulted and parameterised, so they can be changed in the PCB array entry. (Size is settable, since I have seen at least two different sized buzzers used on PCBs.)

### CODE REVIEW

**Comment by nophead** [comment]
There isn't a test for this. Normally I only create PCB parts to put on a PCB so that PCB become the test case.

Perhaps we should have a dummy PCB with an example of each components.

**Comment by martinbudden** [comment]
I'm using this on a RepRap Smart Controller PCB and also a BigTreeTech TFT 3.5 V3.0 controller PCB. I can submit a PR for either or both of those if you like.

A dummy PCB with an example of each component is a good idea.

**Comment by nophead** [comment]
Yes please add those as they are useful to people want to make enclosures.

**Comment by martinbudden** [comment]
I remember why I didn't submit those two - I need a potentiometer on the board for the RepRap Smart Controller, and a usb_A (single slot) for the TFT. I'll get those done and then submit the boards.

**Pull request merged**
